name: CIFajar

on: [push]

jobs:
  eslint:
    name: Lint code base 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Initial packages
        run: npm i
      - name: Run jest testing
        run: npm test

